npmAuditRegistry: "https://registry.npmjs.org/:_authToken=${NPM_TOKEN}"
npmAuthToken: "${NPM_TOKEN}"
npmRegistryServer: "https://registry.npmjs.org"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
